---
permalink: protect-scc/concept_snapcenter_custom_plug_ins_overview.html 
sidebar: sidebar 
keywords: SnapCenter Custom Plug-ins 
summary: È possibile sviluppare plug-in personalizzati per le applicazioni utilizzate e quindi utilizzare SnapCenter per eseguire il backup, il ripristino o la clonazione di tali applicazioni. Come altri plug-in SnapCenter, i plug-in personalizzati fungono da componenti lato host del software NetAppSnap Center, consentendo la protezione dei dati e la gestione delle risorse applicative. 
---
= Panoramica sui plug-in personalizzati di SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile sviluppare plug-in personalizzati per le applicazioni utilizzate e quindi utilizzare SnapCenter per eseguire il backup, il ripristino o la clonazione di tali applicazioni. Come altri plug-in SnapCenter, i plug-in personalizzati agiscono come componenti lato host del software NetApp SnapCenter, consentendo la protezione dei dati e la gestione delle risorse applicative.

Una volta installati i plug-in personalizzati, è possibile utilizzare SnapCenter con la tecnologia NetApp SnapMirror per creare copie mirror dei set di backup su un altro volume e utilizzare la tecnologia NetApp SnapVault per eseguire la replica del backup disk-to-disk. I plug-in personalizzati possono essere utilizzati in ambienti Windows e Linux.


NOTE: SnapCenterCLI non supporta i comandi dei plug-in personalizzati di SnapCenter.

NetApp offre plug-in personalizzati MySQL e DB2 con il software SnapCenter 2.0 e versioni successive e plug-in personalizzato MongoDB dalla versione 3.0 e successive. Questi plug-in possono essere scaricati da https://automationstore.netapp.com/home.shtml["Storage Automation Store di NetApp"^].


NOTE: I plug-in personalizzati MySQL, DB2 e MongoDB sono supportati solo dalle community NetApp.

È possibile creare plug-in personalizzati facendo riferimento a. link:concept_develop_a_plug_in_for_your_application.html["Sviluppare un plug-in per l'applicazione"^].
